In [7]:
import pandas as pd

### Reading a .csv from a url with pandas

Target Website: https://www.football-data.co.uk/data.php

In [13]:
#READING A SINGLE CSV FROM TARGET FILE
df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [16]:
#Showing the DataFrame:
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,E0,21/03/2026,17:30,Everton,Chelsea,3,0,H,1,0,...,1.88,1.98,NaN,NaN,2.15,1.98,1.98,1.82,1.96,2.03
305,E0,21/03/2026,20:00,Leeds,Brentford,0,0,D,0,0,...,2.05,1.80,NaN,NaN,2.12,1.83,2.04,1.76,2.12,1.87
306,E0,22/03/2026,12:00,Newcastle,Sunderland,1,2,A,1,0,...,1.93,1.93,NaN,NaN,2.18,1.96,1.95,1.84,1.99,2.00
307,E0,22/03/2026,14:15,Aston Villa,West Ham,2,0,H,1,0,...,2.00,1.85,NaN,NaN,2.00,1.90,1.93,1.84,2.04,1.95
308,E0,22/03/2026,14:15,Tottenham,Nott'm Forest,0,3,A,0,1,...,2.03,1.83,NaN,NaN,2.12,1.83,2.04,1.76,2.13,1.87

In [18]:
#Renaming columns:
df_premier21.rename(columns = {'FTHG' : 'home_goals', 
                               'FTAG' : 'away_goals'}, inplace = True)
#Inplace makes sure the change is reflected in the orignal.

### 2. Reading from multiple .csv files
    
       Link Structure: Root + season + league

https://www.football-data.co.uk/mmz4281/2122/E0.csv
\
https://www.football-data.co.uk/mmz4281/2122/E1.csv
\
https://www.football-data.co.uk/mmz4281/2122/E2.csv
\
https://www.football-data.co.uk/mmz4281/2122/E3.csv
\
https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [3]:
#Create a root variable
root = "https://www.football-data.co.uk/mmz4281/"

In [11]:
#Creating a list of leagues:
leagues = ['E0', 'E1','E2','E3','EC']

#Creating a list of dataframes
frames = []

#Looping through leagues, read multiple csv and append it into a list:

for league in leagues:
    #Without specifying the encoding it will throw error: UnicodeDecodeError
    #encoding='unicode_escape' is a special codec used to convert Unicode strings into a byte sequence (or vice versa) 
    #that represents characters using Python's string literal escape sequences (e.g., \uXXXX or \xXX)
    df = pd.read_csv(root + '2122'+ '/' + league + '.csv', encoding='unicode_escape')
    frames.append(df)

In [12]:
#Checking for length of Frames:
len(frames)

5

In [13]:
#Show the 1st element
frames[0]

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89


## 2.2 Multiple seasons

In [16]:
#Looping through range of seasons and inserting new columns:
#Creating a list of leagues:
leagues = ['E0','E2','E3']

#Creating a list of dataframes
frames = []

#Looping through range of seasons and inserting new columns:
for league in leagues:
    for season in range(15, 21):
        df = pd.read_csv(root + str(season) + str(season +1)+ '/' + league + '.csv', encoding='unicode_escape')
        #df.insert(index position, name of column, values)
        df.insert(1, 'season', season)
        frames.append(df)

In [17]:
#Total frames = season * league = 18
len(frames)

18

In [19]:
#Showing 1st and last column
frames[-1]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,20,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,20,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,20,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,20,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,20,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,20,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,20,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,20,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,20,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,20,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86